apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: i4mk9chwx-python 
  janus-idp.io/tekton: i4mk9chwx-python
  backstage.io/kubernetes-id: i4mk9chwx-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i4mk9chwx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml